### PR TITLE
added new templates for getting labels in different languages from JR…

### PR DESCRIPTION
**Pull request by fsasaki**
@bjdmeest , can you have a look at these two new templates and if they are OK can you merge them? @jnehring , can you add the templates 4517 and 4518 to the freme server dev and life with the admin user? Thanks a lot in advance.

### CODE REVIEW

**Comment by jnehring** [comment]
@bgrusdt please

* change the user of the two templates to "admin" on freme-live
* copy the templates to the database of freme-dev

**Comment by bjdmeest** [comment]
Let me know when the templates are available, then I can merge :)

2016-10-12 9:45 GMT+02:00 Jan Nehring <notifications@github.com>:

**Comment by jnehring** [comment]
I moved the templates.

**Comment by bjdmeest** [comment]
@fsasaki, could you give an example where this should work? I tried the current example text to detect the concepts from europeana, but the templates didn't give any results

**Comment by fsasaki** [comment]
>could you give an example where this should work? 

Sure, the text "I know Angela Merkel" gives results for the two new templates, at least in my local installation. Does it work for you?

**Comment by bjdmeest** [comment]
What endpoint do you use to detect the concepts?

2016-10-12 10:57 GMT+02:00 Felix Sasaki <notifications@github.com>:

**Comment by fsasaki** [comment]
dbpedia

2016-10-12 10:58 GMT+02:00 Ben De Meester <notifications@github.com>:

**Comment by bjdmeest** [comment]
Ah yes, I was assuming europeana :). Looks good!

**Comment by fsasaki** [comment]
Thanks! I will then delete the new-templates branch.

**Pull request merged**
